pip install numpy
pip install kivy
pip install kivy-deps.angle
pip install kivy-deps.sdl2
pip install kivy-garden
pip install matplotlib
pip install opencv-python
pip install Pillow
pip install pixelink
pip install pixelinkWrapper
pip install wafermap
pip install wfmap